# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83efaf713ecc446847462ca484c9e3b7fcfdb89d80d2be93f5bd58021c122967f341fe822dcc0ee1f4f548d0c5b8772ec5d13f714c14b5d5c4c84ccabb47015f

test:
  secret_key_base: 3d0d7310ad92a156ce1649494541fe6e5887b422cf5f2ebd375f26863c0890c4e7826f0fa64ce89def4f449b3c3aecb55148a1bf1e0d6c364f366ecc0fd39117

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
